version: "3"
services:
    app_symfony:
        container_name: app_symfony
        ports:
            - 8081:8000
        build:
            context: docker/app_symfony
        command: symfony serve
        volumes:
            - "./src/app_symfony:/var/www/app_symfony/public_html"
        networks:
            - internal

    app_go:
        container_name: app_go
        depends_on:
            - sql
            - key_storage
        ports:
            - "8082:8088"
        build:
            context: src/app_go
        env_file:
            - "./env/sql.env"
            - "./env/redis.env"
            - "./env/postgres.env"
        volumes:
            - "./src/app_go:/var/www/app_go/public_html"
        networks:
            - internal

    app_fastapi:
        container_name: app_fastapi
        depends_on:
            - sql
            - key_storage
        ports:
            - "8083:80"
        build:
            context: src/app_fastapi
        env_file:
            - "./env/sql.env"
            - "./env/redis.env"
            - "./env/postgres.env"
        volumes:
            - "./src/app_fastapi:/code"
        networks:
            - internal

    key_storage:
        image: redis:7.0-alpine
        container_name: redis
        ports:
            - 16379:6379
        networks:
            - internal

    sql:
        build:
            context: docker/db_sql
        env_file:
            - "./env/sql.env"
        volumes:
            - "./docker/db_sql/data:/var/lib/mysql"
        ports:
            - "3326:3306"
        networks:
            - internal

    postgres:
        image: 'postgres:16.2-alpine'
        env_file:
            - "./env/postgres.env"
        volumes:
            - "./docker/db_postgres/data:/var/lib/postgresql/data"
        ports:
            - '15432:5432'
        networks:
            - internal

    k6:
        image: grafana/k6
        volumes:
            - ./src/k6:/app
        networks:
            - internal

networks:
    internal:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 192.168.220.0/28
